FROM alpine:3.23

ENV UID=1337 \
    GID=1337

RUN apk add --no-cache ffmpeg su-exec ca-certificates bash jq curl yq-go lottieconverter

ARG EXECUTABLE=./mautrix-fluxer
COPY $EXECUTABLE /usr/bin/mautrix-fluxer
COPY ./example-config.yaml /opt/mautrix-fluxer/example-config.yaml
COPY ./docker-run.sh /docker-run.sh
VOLUME /data
WORKDIR /data

CMD ["/docker-run.sh"]
